name: Build TWRP

on:
  push:
    branches:
      - twrp-11
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick libncurses-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk python-is-python3

      - name: 🔄 Get repo
        run: |
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
         chmod +x ~/repo.1
         mv ~/repo.1 ~/.local/bin/repo

      
      - name: 🔄 Sync TWRP Sources
        run: |
          mkdir -p ~/twrp
          cd ~/twrp
          ~/.local/bin/repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11 --depth=1
          ~/.local/bin/repo sync -j$(nproc) --force-sync

      - name: 📂 Clone Device Tree
        run: |
          cd ~/twrp/device
          git clone --depth=1 https://github.com/opsonc/twrp_device_hmd_IRM_sprout.git hmd/IRM_sprout

      - name: 🔧 Build TWRP Recovery
        run: |
          cd ~/twrp
          source build/envsetup.sh
          lunch twrp_IRM_sprout-eng
          make clean
          make recoveryimage -j$(nproc)

      - name: 📤 Upload Built Recovery
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-Recovery
          path: ~/twrp/out/target/product/IRM_sprout/recovery.img
